### ISSUE TITLE
Error conecting from server to state server

### ISSUE THREAD

**Issue by tarilo** [SocketCluster/scc-state#14]
We try to connect from one server to state server and het this error

{ CompatibilityError: The undefined@undefined at address ::ffff:xxxxxx is incompatible with the scc-state@^6.0.3. Please, update the undefined up to version ^6.0.0

**Comment by MegaGM** [comment]
@tarilo Since version 6.0.0 `scc-state` throws the CompatibilityError and rejects connection if an incompatible component is trying to connect to the `scc-state`. The error indicates that you've updated not all of the `scc-*` components in your cluster, some of them are outdated and incompatible with others. You probably forgot to update `scc-broker-client`, which is required inside your `broker.js`.

Aside from that, you see the `undefined@undefined` because `scc-broker` and `scc-broker-client`, until version 6.0.0, don't know about this feature. The compatibility errors are intended to look like that:
> { CompatibilityError: The scc-broker@3.0.0 at address ::ffff:127.0.0.1:8888 is incompatible with the scc-state@6.0.0. Please, update the scc-broker up to version ^6.0.0

PR is there https://github.com/SocketCluster/scc-state/pull/15

EDIT: PR has been merged. Please, tell us if you still have some kind of issues.

**Comment by tarilo** [comment]
Correct, updating scc-broker-client on the server works fine
